# Generated by Django 2.1.5 on 2019-05-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=120)),
                ('app_description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/')),
                ('android_app_file', models.FileField(upload_to='android_apps/')),
                ('ios_app_file', models.FileField(upload_to='ios_apps/')),
            ],
            options={
                'db_table': 'phone_app',
            },
        ),
    ]
