# Generated by Django 2.1.5 on 2019-05-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneapp',
            name='android_app_file',
            field=models.FileField(blank=True, null=True, upload_to='android_apps/'),
        ),
        migrations.AlterField(
            model_name='phoneapp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='phoneapp',
            name='ios_app_file',
            field=models.FileField(blank=True, null=True, upload_to='ios_apps/'),
        ),
    ]
