# Generated by Django 2.1.5 on 2019-01-29 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_category',
            field=models.CharField(default='Machine Learning', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
