# Generated by Django 2.1.5 on 2019-01-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190129_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies_used1',
            field=models.CharField(default='nothing', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_used2',
            field=models.CharField(default='nothing', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_used3',
            field=models.CharField(default='nothing', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies_used4',
            field=models.CharField(default='nothing', max_length=120),
        ),
    ]
