# Generated by Django 2.1.5 on 2019-03-20 21:48

from django.db import migrations, models
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190130_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_presentation',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', validators=[project.validators.pdf_validator]),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies_used1',
            field=models.CharField(default='N/A', max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies_used2',
            field=models.CharField(default='N/A', max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies_used3',
            field=models.CharField(default='N/A', max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies_used4',
            field=models.CharField(default='N/A', max_length=120),
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
